import React from 'react';
import { MergeMode, ToolType } from './types';

type ExampleTable = {
  beforeTitle: string;
  beforeHeaders: string[];
  beforeRows: string[][];
  afterTitle: string;
  afterHeaders: string[];
  afterRows: string[][];
  note: string;
};

type Page = {
  guideTitle: string;
  how: string[];
  overviewTitle: string;
  overview: string;
  details: [string, string][];
  uses: string[];
  example: ExampleTable;
  behavior: [string, string, string][];
  issues: [string, string][];
  faq: [string, string][];
  related: [string, string, string][];
};

const PAGES: Record<ToolType, Page> = {
  merge: {
    guideTitle: 'How to merge Excel files online',
    how: ['Select two or more XLSX, XLS, or CSV files.','Choose Append Rows for similar tables or Keep Sheets for separate worksheets.','Arrange the files in the order they should be processed.','Configure source columns and identical-row removal.','Merge, download, and verify the workbook in Excel.'],
    overviewTitle: 'Combine Excel workbooks without confusing the output structure',
    overview: 'Merging workbooks can mean two different things: appending similar records into one table or keeping source worksheets as separate tabs. Choosing the correct mode before processing prevents duplicated headers, unexpected blank columns, and mixed report layouts.',
    details: [['Merge Excel files into one sheet','Append Rows reads worksheet tables and aligns values by header name. It is best for monthly reports, exports, inventories, and other similarly structured data.'],['Combine Excel workbooks and keep every sheet','Keep Sheets places supported source worksheets into one output workbook and renames duplicate sheet names when necessary.'],['Merge files with different columns','Different header names become separate output columns. Standardize headers such as Customer ID versus CustomerID before merging when they represent the same field.']],
    uses: ['Combine monthly sales or expense reports.','Consolidate inventory exports from several locations.','Append survey or CRM exports with matching headers.','Keep unrelated reports as separate tabs in one workbook.'],
    example: {beforeTitle:'Two source files',beforeHeaders:['File','Date','Order ID','Revenue'],beforeRows:[['January.xlsx','2026-01-04','A-101','$125'],['February.xlsx','2026-02-02','B-204','$180']],afterTitle:'Append Rows output',afterHeaders:['Date','Order ID','Revenue','Source File'],afterRows:[['2026-01-04','A-101','$125','January.xlsx'],['2026-02-02','B-204','$180','February.xlsx']],note:'Keep Sheets mode would create separate January and February tabs instead of one combined table.'},
    behavior: [['Header alignment','Columns are matched by header text.','Standardize equivalent header names first.'],['Formulas','Append Rows focuses on values readable by the library.','Do not rely on formulas being recalculated.'],['Formatting and charts','Advanced workbook presentation may change.','Keep originals and inspect the downloaded file.'],['Duplicates','Completely identical rows can be removed.','This is not key-based deduplication.']],
    issues: [['Columns do not line up','Standardize header names before merging. Spaces, punctuation, and spelling differences create separate columns.'],['Dates look different','Excel serial dates, text dates, and regional formats may be interpreted differently. Review all date columns.'],['The result is blank','Protected, encrypted, damaged, or connection-based workbooks may not expose readable table data.'],['The browser becomes slow','Large workbooks use browser memory. Process fewer files or reduce workbook size.']],
    faq: [['Can files have different columns?','Yes. Different headers become separate output columns.'],['Can I combine XLS and XLSX?','Yes, within the features supported by the browser spreadsheet library.'],['Are formulas and formatting preserved?','Append Rows focuses on table data. Keep Sheets may retain some worksheet features, but formulas, charts, macros, styling, and links must be checked.'],['Are files uploaded?','Spreadsheet contents are processed in the browser tab and are not sent to an application processing server.'],['How many files can I merge?','There is no fixed count, but browser memory and file complexity create practical limits.'],['Can I remove duplicates?','The tool removes only rows that are completely identical across all output columns.']],
    related: [['/merge-excel-files-keep-sheets/','Merge Excel Files and Keep Sheets','Combine workbooks while keeping source worksheets as separate tabs.'],['/merge-csv-files/','Merge CSV Files','Append multiple CSV exports into one XLSX worksheet.'],['/split-excel-by-rows/','Split Excel by Rows','Break a large first worksheet into smaller XLSX files.']],
  },
  'merge-csv': {
    guideTitle: 'How to merge multiple CSV files into Excel',
    how: ['Select at least two CSV files.','Confirm that the first row contains column headers.','Choose whether to add source columns or remove identical rows.','Merge and download the XLSX result.','Verify delimiters, accents, dates, leading zeros, and column alignment.'],
    overviewTitle: 'Merge recurring CSV exports into one usable workbook',
    overview: 'CSV files are plain-text tables. The merge works best when every file uses the same delimiter, encoding, and header names. The output is an XLSX workbook so the combined data can be reviewed and formatted in Excel.',
    details: [['Merge CSV files with the same headers','Records are appended under matching column names, making this suitable for recurring analytics, CRM, transaction, and inventory exports.'],['Merge CSV files with different columns','New header names create additional columns. Rows from files without those fields remain blank in the corresponding columns.'],['Preserve the source of each record','Enable source columns to add the original file and sheet information to each output row.']],
    uses: ['Combine recurring analytics or CRM exports.','Append similarly structured transaction or log files.','Merge contact lists while retaining source-file information.','Turn multiple CSV downloads into one workbook for review.'],
    example: {beforeTitle:'Two CSV exports',beforeHeaders:['File','Email','Name','Country'],beforeRows:[['leads-us.csv','ana@example.com','Ana','US'],['leads-es.csv','luis@example.com','Luis','ES']],afterTitle:'Merged XLSX worksheet',afterHeaders:['Email','Name','Country','Source File'],afterRows:[['ana@example.com','Ana','US','leads-us.csv'],['luis@example.com','Luis','ES','leads-es.csv']],note:'A Phone column present in only one source file would be added as a new output column.'},
    behavior: [['Encoding','UTF-8 is the most reliable.','Re-export broken text as UTF-8.'],['Delimiter','Standard comma-separated input works best.','Semicolon or tab parsing may vary.'],['Leading zeros','Text-like IDs may be interpreted as numbers.','Verify ZIP codes, SKUs, and phone values.'],['Formatting','CSV contains no Excel styling.','Apply formatting after conversion.']],
    issues: [['Everything appears in one column','The source may use a semicolon, tab, or nonstandard delimiter. Re-export as comma-separated CSV.'],['Accented characters are broken','Save the source file with UTF-8 encoding before merging.'],['Headers repeat inside the data','Remove embedded header rows from source files before merging.'],['Columns are duplicated','Equivalent fields use different names. Standardize them before processing.']],
    faq: [['Can CSV files have different columns?','Yes. Different headers create separate output columns.'],['Does CSV preserve Excel formatting?','No. CSV contains plain table text only.'],['What is downloaded?','One XLSX workbook with a merged worksheet.'],['Can it read semicolon-separated files?','Parser behavior varies; standard comma-separated UTF-8 input is most reliable.'],['Can duplicate rows be removed?','Completely identical output rows can be removed.'],['Are CSV contents uploaded?','No. Processing occurs in the current browser tab.']],
    related: [['/','Merge Excel Files','Combine XLSX, XLS, and CSV files using two output modes.'],['/csv-to-excel/','CSV to Excel Converter','Convert one CSV file into a single-sheet XLSX workbook.'],['/excel-to-csv/','Excel to CSV Converter','Export the first Excel worksheet as UTF-8 CSV.']],
  },
  splitter: {
    guideTitle: 'How to split an Excel file into smaller files by rows',
    how: ['Select one XLSX or XLS workbook.','Enter the number of data rows for each output file.','Start the split operation.','Download every generated XLSX part.','Check repeated headers, row ranges, and file count.'],
    overviewTitle: 'Split a large Excel worksheet into predictable row batches',
    overview: 'The splitter processes the first worksheet, treats its first row as the header, and repeats that header in every generated part. It is designed for upload limits, batch review, and manageable distribution—not for splitting by category or column value.',
    details: [['Calculate how many output files will be created','Divide the number of data rows by the selected rows-per-file value and round up. Ten thousand rows split by one thousand creates ten files.'],['Repeat the header row automatically','The first worksheet row is copied to every output so each part remains understandable when opened separately.'],['Understand the current scope','Only the first worksheet is split. Other worksheets and advanced workbook features are not included in the generated parts.']],
    uses: ['Meet CRM, accounting, or marketplace upload row limits.','Create predictable batches for review or processing.','Distribute smaller lists to separate team members.','Reduce the memory required to open one very large table.'],
    example: {beforeTitle:'Original first worksheet',beforeHeaders:['Row range','Customer ID','Status'],beforeRows:[['1–1000','C0001…C1000','Mixed'],['1001–2000','C1001…C2000','Mixed']],afterTitle:'Output files at 1,000 rows each',afterHeaders:['File','Header repeated','Data rows'],afterRows:[['part-1.xlsx','Yes','1–1000'],['part-2.xlsx','Yes','1001–2000']],note:'A worksheet with 10,000 data rows produces 10 output files when the batch size is 1,000.'},
    behavior: [['Worksheets','Only the first worksheet is processed.','Move the required table to the first tab.'],['Header row','The first row is repeated in every part.','Confirm row one contains headers.'],['Split rule','Fixed number of rows per file.','It does not group by a column value.'],['Workbook features','Output focuses on table data.','Verify formulas, styling, charts, and links.']],
    issues: [['Too many or too few output files','Confirm the row count excludes the header and check the rows-per-file setting.'],['A header is missing or incorrect','The first row is always treated as the header. Fix the source workbook before splitting.'],['Only one worksheet was processed','This is the designed behavior of the current version. Split other sheets separately.'],['Files are slow to generate','Large tables consume browser memory. Use a larger batch size or reduce the source workbook.']],
    faq: [['Does each part include headers?','Yes, the first row is repeated in every output file.'],['Can every worksheet be split?','No. The current version processes the first worksheet.'],['Can it split by a column value?','No. It splits by a fixed number of rows.'],['Is processing local?','Yes. It runs in the browser tab.'],['How many files will be created?','The data row count divided by rows per file, rounded up.'],['Are formulas preserved?','Generated parts focus on readable table data; advanced features must be checked.']],
    related: [['/','Merge Excel Files','Combine spreadsheet files after batch processing.'],['/merge-excel-files-keep-sheets/','Keep Excel Sheets','Place source worksheets into one output workbook.'],['/excel-to-csv/','Excel to CSV','Export the first worksheet to a flat UTF-8 CSV file.']],
  },
  'excel-to-csv': {
    guideTitle: 'How to convert Excel to CSV online',
    how: ['Select one XLSX or XLS workbook.','Place the required table in the first worksheet.','Run the Excel-to-CSV conversion.','Download the UTF-8 CSV file.','Verify text, dates, leading zeros, delimiters, and formula values.'],
    overviewTitle: 'Convert the first Excel worksheet into a portable flat file',
    overview: 'CSV stores one plain table and cannot represent an entire workbook. The converter exports the first worksheet as UTF-8 CSV, making it useful for database imports, scripts, and systems that accept delimited text.',
    details: [['Only the first worksheet is exported','CSV has no worksheet concept, so additional tabs are not included. Move or copy the required table to the first worksheet.'],['Formatting is removed by design','Fonts, colors, merged cells, images, charts, comments, and workbook settings cannot be stored in CSV.'],['Formula values require verification','The parser may read available cached values, but it does not run the Excel calculation engine.']],
    uses: ['Prepare data for database or CRM imports.','Create flat files for scripts and command-line tools.','Move table data into CSV-only systems.','Produce UTF-8 text for cross-platform exchange.'],
    example: {beforeTitle:'Excel first worksheet',beforeHeaders:['Product','SKU','Price'],beforeRows:[['Desk Lamp','00125','$29.00'],['Wall Clock','00840','$18.50']],afterTitle:'UTF-8 CSV output',afterHeaders:['Product','SKU','Price'],afterRows:[['Desk Lamp','00125','29'],['Wall Clock','00840','18.5']],note:'Excel styling is removed. Verify that identifiers such as 00125 retain the intended leading zeros.'},
    behavior: [['Worksheets','Only the first worksheet is exported.','Move the required data to the first tab.'],['Formulas','CSV stores values, not formulas.','Confirm calculated values after export.'],['Formatting','Not supported by CSV.','Expect plain rows and columns.'],['Encoding','Output is UTF-8.','Check the importing system’s encoding setting.']],
    issues: [['Leading zeros disappear','The importing application may treat identifiers as numbers. Import those columns as text.'],['Dates change format','CSV contains text values and the next program may apply its own regional date interpretation.'],['Formula results look stale','The browser library does not recalculate the workbook. Save recalculated values in Excel first.'],['The wrong worksheet was converted','Only the first worksheet is exported. Reorder the workbook tabs.']],
    faq: [['Which sheet is converted?','Only the first worksheet.'],['Are formulas preserved?','No. CSV stores available values rather than workbook formulas.'],['Is the output UTF-8?','Yes.'],['Can CSV contain several tabs?','No. CSV is one flat table.'],['Are charts and images included?','No. CSV cannot store them.'],['Why do leading zeros change?','Spreadsheet programs often infer numeric types when opening CSV.']],
    related: [['/csv-to-excel/','CSV to Excel Converter','Turn a CSV file into a simple XLSX workbook.'],['/merge-csv-files/','Merge CSV Files','Combine several CSV exports into one XLSX worksheet.'],['/json-to-excel/','JSON to Excel','Convert flat JSON records into a worksheet.']],
  },
  'csv-to-excel': {
    guideTitle: 'How to convert CSV to Excel without losing important text values',
    how: ['Select one CSV file.','Confirm that it uses a supported delimiter and readable encoding.','Convert the file to XLSX.','Download and open the workbook.','Verify columns, accents, dates, long numbers, and leading zeros.'],
    overviewTitle: 'Turn a plain CSV table into a simple Excel workbook',
    overview: 'The converter creates one XLSX workbook with one worksheet. It does not invent formulas or styling, but the Excel format makes the table easier to review, format, filter, and share.',
    details: [['Protect identifiers with leading zeros','ZIP codes, SKUs, account references, and phone values may be interpreted as numbers. Review these columns and format them as text when required.'],['Check delimiters before converting','Standard comma-separated input is the safest. Semicolon, tab, and regional CSV formats can result in one-column output.'],['Review automatic date and number interpretation','Text that resembles a date, large integer, or scientific number may be interpreted differently after opening in Excel.']],
    uses: ['Review CSV exports in Excel.','Share plain-text data as an XLSX workbook.','Apply filters and spreadsheet formatting after conversion.','Prepare one CSV table for nontechnical users.'],
    example: {beforeTitle:'CSV source',beforeHeaders:['Name','ZIP Code','Status'],beforeRows:[['Ana','00125','Active'],['Luis','00908','Pending']],afterTitle:'Single-sheet XLSX',afterHeaders:['Name','ZIP Code','Status'],afterRows:[['Ana','00125','Active'],['Luis','00908','Pending']],note:'Open the workbook and verify that ZIP Code values remain text rather than becoming 125 and 908.'},
    behavior: [['Worksheets','One worksheet is created.','Use Merge CSV for multiple files.'],['Styling','No custom styling is inferred.','Apply formatting after conversion.'],['Data types','Parser and Excel may infer values.','Check identifiers, dates, and long numbers.'],['Encoding','Readable UTF-8 works best.','Re-save broken source text as UTF-8.']],
    issues: [['All data appears in one column','The source likely uses a different delimiter. Re-export as standard comma-separated CSV.'],['Accented characters are broken','Convert the source encoding to UTF-8.'],['Leading zeros disappear','Format identifier columns as text and review the source values.'],['Large numbers become scientific notation','Format the destination column as text or use an import workflow with explicit types.']],
    faq: [['Does it add formulas or styling?','No. It creates a simple worksheet.'],['Can I convert many CSV files?','Use the Merge CSV Files page.'],['How many sheets are created?','One.'],['Is the CSV uploaded?','No. Conversion runs in the browser tab.'],['Why is everything in one column?','The delimiter may not be a standard comma.'],['Can Excel change dates automatically?','Yes. Review date-like text after opening the workbook.']],
    related: [['/merge-csv-files/','Merge CSV Files','Combine several CSV files into one XLSX worksheet.'],['/excel-to-csv/','Excel to CSV Converter','Export the first Excel worksheet as UTF-8 CSV.'],['/','Merge Excel Files','Combine Excel and CSV sources using Append Rows or Keep Sheets.']],
  },
  'json-to-excel': {
    guideTitle: 'How to convert JSON to Excel online',
    how: ['Select one valid JSON file.','Use a flat array of objects for the clearest table.','Run the JSON-to-Excel conversion.','Download the generated XLSX workbook.','Review nested values, nulls, arrays, and inferred data types.'],
    overviewTitle: 'Convert flat JSON records into rows and columns',
    overview: 'A flat array of similarly shaped objects maps naturally to a worksheet: object keys become column headers and each object becomes one row. Nested objects and arrays should be flattened before conversion when separate columns are required.',
    details: [['Best JSON structure for Excel','Use an array such as [{"name":"Ana","score":92},{"name":"Luis","score":88}]. Consistent keys produce consistent columns.'],['Single objects create one row','A single JSON object can be converted, but it produces only one worksheet record.'],['Nested JSON is not relationally normalized','Objects and arrays inside records are not automatically expanded into linked worksheets or database-style tables.']],
    uses: ['Convert saved API responses for business users.','Share developer data with Excel users.','Inspect object records as rows.','Create a worksheet from exported application data.'],
    example: {beforeTitle:'JSON array',beforeHeaders:['JSON object 1','JSON object 2'],beforeRows:[['{"name":"Ana","score":92}','{"name":"Luis","score":88}']],afterTitle:'Excel worksheet',afterHeaders:['name','score'],afterRows:[['Ana','92'],['Luis','88']],note:'Nested values such as {"address":{"city":"Austin"}} should be flattened to address_city before conversion when a separate column is needed.'},
    behavior: [['Top-level array','Each object becomes a row.','Use consistent object keys.'],['Single object','Creates one row.','Use an array for multiple records.'],['Nested objects','Not automatically normalized.','Flatten them before conversion.'],['Null and missing keys','May create blank cells.','Review required columns after download.']],
    issues: [['The JSON is invalid','Check quotation marks, commas, brackets, and trailing characters with a JSON validator.'],['Nested objects appear incorrectly','Flatten nested keys before conversion.'],['Only one row is created','The source is one object rather than an array of objects.'],['Columns differ between rows','Objects use inconsistent keys. Standardize the JSON structure.']],
    faq: [['What structure works best?','A flat array of objects with consistent keys.'],['Can it create related sheets?','No. It creates one worksheet.'],['Are nested arrays flattened?','No.'],['Can invalid JSON be converted?','No. The file must be valid JSON.'],['What happens to null values?','They generally become blank worksheet cells.'],['Can one JSON object be converted?','Yes. It creates one record row.']],
    related: [['/csv-to-excel/','CSV to Excel Converter','Convert one CSV table into an XLSX workbook.'],['/merge-csv-files/','Merge CSV Files','Combine multiple text-table exports.'],['/','Merge Excel Files','Combine spreadsheet workbooks and table exports.']],
  },
};

const Heading=({children}:{children:React.ReactNode})=><h2 className="text-3xl font-black tracking-tight md:text-4xl">{children}</h2>;

function DataTable({headers,rows}:{headers:string[];rows:string[][]}){
  return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-slate-900 text-white"><tr>{headers.map(h=><th key={h} className="p-4 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={`${i}-${j}`} className="p-4 text-slate-600">{cell}</td>)}</tr>)}</tbody></table></div>;
}

export default function SeoContent({tool,mergeMode}:{tool:ToolType;mergeMode:MergeMode}){
  const p=PAGES[tool];
  return <div className="border-t border-slate-100">
    <section className="mx-auto max-w-6xl px-5 py-16"><Heading>{p.guideTitle}</Heading><ol className="mt-8 grid gap-4 md:grid-cols-5">{p.how.map((x,i)=><li key={x} className="rounded-2xl border p-5 text-sm leading-7 text-slate-600"><b className="mb-3 flex h-9 w-9 items-center justify-center rounded-full bg-slate-900 text-white">{i+1}</b>{x}</li>)}</ol></section>
    <section className="border-y bg-slate-50 px-5 py-16"><div className="mx-auto max-w-6xl"><Heading>{p.overviewTitle}</Heading><p className="mt-5 max-w-4xl text-lg leading-8 text-slate-600">{p.overview}</p><div className="mt-8 grid gap-5 md:grid-cols-3">{p.details.map(([title,text])=><article key={title} className="rounded-2xl border bg-white p-6"><h3 className="font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    {tool==='merge'&&<section className="px-5 py-16"><div className="mx-auto max-w-6xl"><Heading>Append Rows vs Keep Sheets</Heading><p className="mt-4 text-slate-600">Current selection: <b>{mergeMode==='append-rows'?'Append Rows':'Keep Sheets'}</b>.</p><div className="mt-8 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-4">Feature</th><th className="p-4">Append Rows</th><th className="p-4">Keep Sheets</th></tr></thead><tbody className="divide-y"><tr><th className="p-4">Output</th><td className="p-4">One combined table</td><td className="p-4">Separate worksheets</td></tr><tr><th className="p-4">Best for</th><td className="p-4">Similar headers</td><td className="p-4">Different layouts</td></tr><tr><th className="p-4">Duplicates</th><td className="p-4">Identical rows can be removed</td><td className="p-4">Not applied</td></tr><tr><th className="p-4">Excel features</th><td className="p-4">Table data focus</td><td className="p-4">Must be verified</td></tr></tbody></table></div></div></section>}
    <section className="border-y bg-slate-50 px-5 py-16"><div className="mx-auto max-w-6xl"><Heading>Before and after example</Heading><div className="mt-8 grid gap-8 lg:grid-cols-2"><div><h3 className="mb-3 text-lg font-black">{p.example.beforeTitle}</h3><DataTable headers={p.example.beforeHeaders} rows={p.example.beforeRows}/></div><div><h3 className="mb-3 text-lg font-black">{p.example.afterTitle}</h3><DataTable headers={p.example.afterHeaders} rows={p.example.afterRows}/></div></div><p className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm leading-7 text-blue-900">{p.example.note}</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-2"><div><Heading>Common use cases</Heading><div className="mt-7 grid gap-4">{p.uses.map(x=><p key={x} className="rounded-2xl border p-5 leading-7 text-slate-600">{x}</p>)}</div></div><div><Heading>Data and output behavior</Heading><div className="mt-7 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-4">Area</th><th className="p-4">What happens</th><th className="p-4">What to check</th></tr></thead><tbody className="divide-y">{p.behavior.map(([area,result,check])=><tr key={area}><th className="p-4">{area}</th><td className="p-4 text-slate-600">{result}</td><td className="p-4 text-slate-600">{check}</td></tr>)}</tbody></table></div><p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-900"><b>Keep the originals.</b> Generated output must be checked before important operational use.</p></div></section>
    <section className="border-y bg-slate-50 px-5 py-16"><div className="mx-auto max-w-6xl"><Heading>Troubleshooting</Heading><div className="mt-8 grid gap-4 md:grid-cols-2">{p.issues.map(([title,text])=><article key={title} className="rounded-2xl border bg-white p-6"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 py-16"><Heading>Frequently asked questions</Heading><div className="mt-8 divide-y rounded-2xl border px-6">{p.faq.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-black">{q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{a}</p></details>)}</div></section>
    <section className="border-t bg-slate-50 px-5 py-16"><div className="mx-auto max-w-6xl"><Heading>Related spreadsheet tools</Heading><div className="mt-8 grid gap-4 md:grid-cols-3">{p.related.map(([href,title,text])=><a key={href} href={href} className="rounded-2xl border bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p><span className="mt-4 inline-block text-sm font-bold">Open tool →</span></a>)}</div></div></section>
  </div>;
}
